/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabelasRouteImport } from './routes/tabelas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoucherIndexRouteImport } from './routes/voucher.index'
import { Route as CampeonatosIndexRouteImport } from './routes/campeonatos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VoucherIdRouteImport } from './routes/voucher.$id'
import { Route as SucessoVoucherRouteImport } from './routes/sucesso.$voucher'
import { Route as StaffPainelRouteImport } from './routes/staff.painel'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as InscricaoCategoryIdRouteImport } from './routes/inscricao.$categoryId'
import { Route as IngressosSlugRouteImport } from './routes/ingressos.$slug'
import { Route as ChavesBracketIdRouteImport } from './routes/chaves.$bracketId'
import { Route as CampeonatosSlugRouteImport } from './routes/campeonatos.$slug'
import { Route as AdminPremiacoesRouteImport } from './routes/admin.premiacoes'
import { Route as AdminInscricoesRouteImport } from './routes/admin.inscricoes'
import { Route as AdminAdministradoresRouteImport } from './routes/admin.administradores'
import { Route as AdminStaffsIndexRouteImport } from './routes/admin.staffs.index'
import { Route as AdminChavesIndexRouteImport } from './routes/admin.chaves.index'
import { Route as AdminCampeonatosIndexRouteImport } from './routes/admin.campeonatos.index'
import { Route as StaffCadastroTokenRouteImport } from './routes/staff.cadastro.$token'
import { Route as PremiacaoCadastroTokenRouteImport } from './routes/premiacao.cadastro.$token'
import { Route as ArbitroCadastroTokenRouteImport } from './routes/arbitro.cadastro.$token'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as ApiPublicAsaasTransferAuthRouteImport } from './routes/api/public/asaas-transfer-auth'
import { Route as AdminStaffsStaffIdRouteImport } from './routes/admin.staffs.$staffId'
import { Route as AdminPortariaIdRouteImport } from './routes/admin.portaria.$id'
import { Route as AdminChavesBracketIdRouteImport } from './routes/admin.chaves.$bracketId'
import { Route as AdminCategoriasCategoryIdRouteImport } from './routes/admin.categorias.$categoryId'
import { Route as AdminCampeonatosIdRouteImport } from './routes/admin.campeonatos.$id'

const TabelasRoute = TabelasRouteImport.update({
  id: '/tabelas',
  path: '/tabelas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherIndexRoute = VoucherIndexRouteImport.update({
  id: '/voucher/',
  path: '/voucher/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosIndexRoute = CampeonatosIndexRouteImport.update({
  id: '/campeonatos/',
  path: '/campeonatos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VoucherIdRoute = VoucherIdRouteImport.update({
  id: '/voucher/$id',
  path: '/voucher/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoVoucherRoute = SucessoVoucherRouteImport.update({
  id: '/sucesso/$voucher',
  path: '/sucesso/$voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPainelRoute = StaffPainelRouteImport.update({
  id: '/staff/painel',
  path: '/staff/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoCategoryIdRoute = InscricaoCategoryIdRouteImport.update({
  id: '/inscricao/$categoryId',
  path: '/inscricao/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const IngressosSlugRoute = IngressosSlugRouteImport.update({
  id: '/ingressos/$slug',
  path: '/ingressos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChavesBracketIdRoute = ChavesBracketIdRouteImport.update({
  id: '/chaves/$bracketId',
  path: '/chaves/$bracketId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosSlugRoute = CampeonatosSlugRouteImport.update({
  id: '/campeonatos/$slug',
  path: '/campeonatos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPremiacoesRoute = AdminPremiacoesRouteImport.update({
  id: '/premiacoes',
  path: '/premiacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInscricoesRoute = AdminInscricoesRouteImport.update({
  id: '/inscricoes',
  path: '/inscricoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministradoresRoute = AdminAdministradoresRouteImport.update({
  id: '/administradores',
  path: '/administradores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffsIndexRoute = AdminStaffsIndexRouteImport.update({
  id: '/staffs/',
  path: '/staffs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChavesIndexRoute = AdminChavesIndexRouteImport.update({
  id: '/chaves/',
  path: '/chaves/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampeonatosIndexRoute = AdminCampeonatosIndexRouteImport.update({
  id: '/campeonatos/',
  path: '/campeonatos/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffCadastroTokenRoute = StaffCadastroTokenRouteImport.update({
  id: '/staff/cadastro/$token',
  path: '/staff/cadastro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiacaoCadastroTokenRoute = PremiacaoCadastroTokenRouteImport.update({
  id: '/premiacao/cadastro/$token',
  path: '/premiacao/cadastro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitroCadastroTokenRoute = ArbitroCadastroTokenRouteImport.update({
  id: '/arbitro/cadastro/$token',
  path: '/arbitro/cadastro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasTransferAuthRoute =
  ApiPublicAsaasTransferAuthRouteImport.update({
    id: '/api/public/asaas-transfer-auth',
    path: '/api/public/asaas-transfer-auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminStaffsStaffIdRoute = AdminStaffsStaffIdRouteImport.update({
  id: '/staffs/$staffId',
  path: '/staffs/$staffId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortariaIdRoute = AdminPortariaIdRouteImport.update({
  id: '/portaria/$id',
  path: '/portaria/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChavesBracketIdRoute = AdminChavesBracketIdRouteImport.update({
  id: '/chaves/$bracketId',
  path: '/chaves/$bracketId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasCategoryIdRoute =
  AdminCategoriasCategoryIdRouteImport.update({
    id: '/categorias/$categoryId',
    path: '/categorias/$categoryId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCampeonatosIdRoute = AdminCampeonatosIdRouteImport.update({
  id: '/campeonatos/$id',
  path: '/campeonatos/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/tabelas': typeof TabelasRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/inscricoes': typeof AdminInscricoesRoute
  '/admin/premiacoes': typeof AdminPremiacoesRoute
  '/campeonatos/$slug': typeof CampeonatosSlugRoute
  '/chaves/$bracketId': typeof ChavesBracketIdRoute
  '/ingressos/$slug': typeof IngressosSlugRoute
  '/inscricao/$categoryId': typeof InscricaoCategoryIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/painel': typeof StaffPainelRoute
  '/sucesso/$voucher': typeof SucessoVoucherRoute
  '/voucher/$id': typeof VoucherIdRoute
  '/admin/': typeof AdminIndexRoute
  '/campeonatos/': typeof CampeonatosIndexRoute
  '/voucher/': typeof VoucherIndexRoute
  '/admin/campeonatos/$id': typeof AdminCampeonatosIdRoute
  '/admin/categorias/$categoryId': typeof AdminCategoriasCategoryIdRoute
  '/admin/chaves/$bracketId': typeof AdminChavesBracketIdRoute
  '/admin/portaria/$id': typeof AdminPortariaIdRoute
  '/admin/staffs/$staffId': typeof AdminStaffsStaffIdRoute
  '/api/public/asaas-transfer-auth': typeof ApiPublicAsaasTransferAuthRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/arbitro/cadastro/$token': typeof ArbitroCadastroTokenRoute
  '/premiacao/cadastro/$token': typeof PremiacaoCadastroTokenRoute
  '/staff/cadastro/$token': typeof StaffCadastroTokenRoute
  '/admin/campeonatos/': typeof AdminCampeonatosIndexRoute
  '/admin/chaves/': typeof AdminChavesIndexRoute
  '/admin/staffs/': typeof AdminStaffsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tabelas': typeof TabelasRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/inscricoes': typeof AdminInscricoesRoute
  '/admin/premiacoes': typeof AdminPremiacoesRoute
  '/campeonatos/$slug': typeof CampeonatosSlugRoute
  '/chaves/$bracketId': typeof ChavesBracketIdRoute
  '/ingressos/$slug': typeof IngressosSlugRoute
  '/inscricao/$categoryId': typeof InscricaoCategoryIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/painel': typeof StaffPainelRoute
  '/sucesso/$voucher': typeof SucessoVoucherRoute
  '/voucher/$id': typeof VoucherIdRoute
  '/admin': typeof AdminIndexRoute
  '/campeonatos': typeof CampeonatosIndexRoute
  '/voucher': typeof VoucherIndexRoute
  '/admin/campeonatos/$id': typeof AdminCampeonatosIdRoute
  '/admin/categorias/$categoryId': typeof AdminCategoriasCategoryIdRoute
  '/admin/chaves/$bracketId': typeof AdminChavesBracketIdRoute
  '/admin/portaria/$id': typeof AdminPortariaIdRoute
  '/admin/staffs/$staffId': typeof AdminStaffsStaffIdRoute
  '/api/public/asaas-transfer-auth': typeof ApiPublicAsaasTransferAuthRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/arbitro/cadastro/$token': typeof ArbitroCadastroTokenRoute
  '/premiacao/cadastro/$token': typeof PremiacaoCadastroTokenRoute
  '/staff/cadastro/$token': typeof StaffCadastroTokenRoute
  '/admin/campeonatos': typeof AdminCampeonatosIndexRoute
  '/admin/chaves': typeof AdminChavesIndexRoute
  '/admin/staffs': typeof AdminStaffsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/tabelas': typeof TabelasRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/inscricoes': typeof AdminInscricoesRoute
  '/admin/premiacoes': typeof AdminPremiacoesRoute
  '/campeonatos/$slug': typeof CampeonatosSlugRoute
  '/chaves/$bracketId': typeof ChavesBracketIdRoute
  '/ingressos/$slug': typeof IngressosSlugRoute
  '/inscricao/$categoryId': typeof InscricaoCategoryIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/painel': typeof StaffPainelRoute
  '/sucesso/$voucher': typeof SucessoVoucherRoute
  '/voucher/$id': typeof VoucherIdRoute
  '/admin/': typeof AdminIndexRoute
  '/campeonatos/': typeof CampeonatosIndexRoute
  '/voucher/': typeof VoucherIndexRoute
  '/admin/campeonatos/$id': typeof AdminCampeonatosIdRoute
  '/admin/categorias/$categoryId': typeof AdminCategoriasCategoryIdRoute
  '/admin/chaves/$bracketId': typeof AdminChavesBracketIdRoute
  '/admin/portaria/$id': typeof AdminPortariaIdRoute
  '/admin/staffs/$staffId': typeof AdminStaffsStaffIdRoute
  '/api/public/asaas-transfer-auth': typeof ApiPublicAsaasTransferAuthRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/arbitro/cadastro/$token': typeof ArbitroCadastroTokenRoute
  '/premiacao/cadastro/$token': typeof PremiacaoCadastroTokenRoute
  '/staff/cadastro/$token': typeof StaffCadastroTokenRoute
  '/admin/campeonatos/': typeof AdminCampeonatosIndexRoute
  '/admin/chaves/': typeof AdminChavesIndexRoute
  '/admin/staffs/': typeof AdminStaffsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/tabelas'
    | '/admin/administradores'
    | '/admin/inscricoes'
    | '/admin/premiacoes'
    | '/campeonatos/$slug'
    | '/chaves/$bracketId'
    | '/ingressos/$slug'
    | '/inscricao/$categoryId'
    | '/staff/login'
    | '/staff/painel'
    | '/sucesso/$voucher'
    | '/voucher/$id'
    | '/admin/'
    | '/campeonatos/'
    | '/voucher/'
    | '/admin/campeonatos/$id'
    | '/admin/categorias/$categoryId'
    | '/admin/chaves/$bracketId'
    | '/admin/portaria/$id'
    | '/admin/staffs/$staffId'
    | '/api/public/asaas-transfer-auth'
    | '/api/public/asaas-webhook'
    | '/arbitro/cadastro/$token'
    | '/premiacao/cadastro/$token'
    | '/staff/cadastro/$token'
    | '/admin/campeonatos/'
    | '/admin/chaves/'
    | '/admin/staffs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tabelas'
    | '/admin/administradores'
    | '/admin/inscricoes'
    | '/admin/premiacoes'
    | '/campeonatos/$slug'
    | '/chaves/$bracketId'
    | '/ingressos/$slug'
    | '/inscricao/$categoryId'
    | '/staff/login'
    | '/staff/painel'
    | '/sucesso/$voucher'
    | '/voucher/$id'
    | '/admin'
    | '/campeonatos'
    | '/voucher'
    | '/admin/campeonatos/$id'
    | '/admin/categorias/$categoryId'
    | '/admin/chaves/$bracketId'
    | '/admin/portaria/$id'
    | '/admin/staffs/$staffId'
    | '/api/public/asaas-transfer-auth'
    | '/api/public/asaas-webhook'
    | '/arbitro/cadastro/$token'
    | '/premiacao/cadastro/$token'
    | '/staff/cadastro/$token'
    | '/admin/campeonatos'
    | '/admin/chaves'
    | '/admin/staffs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/tabelas'
    | '/admin/administradores'
    | '/admin/inscricoes'
    | '/admin/premiacoes'
    | '/campeonatos/$slug'
    | '/chaves/$bracketId'
    | '/ingressos/$slug'
    | '/inscricao/$categoryId'
    | '/staff/login'
    | '/staff/painel'
    | '/sucesso/$voucher'
    | '/voucher/$id'
    | '/admin/'
    | '/campeonatos/'
    | '/voucher/'
    | '/admin/campeonatos/$id'
    | '/admin/categorias/$categoryId'
    | '/admin/chaves/$bracketId'
    | '/admin/portaria/$id'
    | '/admin/staffs/$staffId'
    | '/api/public/asaas-transfer-auth'
    | '/api/public/asaas-webhook'
    | '/arbitro/cadastro/$token'
    | '/premiacao/cadastro/$token'
    | '/staff/cadastro/$token'
    | '/admin/campeonatos/'
    | '/admin/chaves/'
    | '/admin/staffs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  TabelasRoute: typeof TabelasRoute
  CampeonatosSlugRoute: typeof CampeonatosSlugRoute
  ChavesBracketIdRoute: typeof ChavesBracketIdRoute
  IngressosSlugRoute: typeof IngressosSlugRoute
  InscricaoCategoryIdRoute: typeof InscricaoCategoryIdRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffPainelRoute: typeof StaffPainelRoute
  SucessoVoucherRoute: typeof SucessoVoucherRoute
  VoucherIdRoute: typeof VoucherIdRoute
  CampeonatosIndexRoute: typeof CampeonatosIndexRoute
  VoucherIndexRoute: typeof VoucherIndexRoute
  ApiPublicAsaasTransferAuthRoute: typeof ApiPublicAsaasTransferAuthRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ArbitroCadastroTokenRoute: typeof ArbitroCadastroTokenRoute
  PremiacaoCadastroTokenRoute: typeof PremiacaoCadastroTokenRoute
  StaffCadastroTokenRoute: typeof StaffCadastroTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tabelas': {
      id: '/tabelas'
      path: '/tabelas'
      fullPath: '/tabelas'
      preLoaderRoute: typeof TabelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher/': {
      id: '/voucher/'
      path: '/voucher'
      fullPath: '/voucher/'
      preLoaderRoute: typeof VoucherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/': {
      id: '/campeonatos/'
      path: '/campeonatos'
      fullPath: '/campeonatos/'
      preLoaderRoute: typeof CampeonatosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/voucher/$id': {
      id: '/voucher/$id'
      path: '/voucher/$id'
      fullPath: '/voucher/$id'
      preLoaderRoute: typeof VoucherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso/$voucher': {
      id: '/sucesso/$voucher'
      path: '/sucesso/$voucher'
      fullPath: '/sucesso/$voucher'
      preLoaderRoute: typeof SucessoVoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/painel': {
      id: '/staff/painel'
      path: '/staff/painel'
      fullPath: '/staff/painel'
      preLoaderRoute: typeof StaffPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$categoryId': {
      id: '/inscricao/$categoryId'
      path: '/inscricao/$categoryId'
      fullPath: '/inscricao/$categoryId'
      preLoaderRoute: typeof InscricaoCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingressos/$slug': {
      id: '/ingressos/$slug'
      path: '/ingressos/$slug'
      fullPath: '/ingressos/$slug'
      preLoaderRoute: typeof IngressosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chaves/$bracketId': {
      id: '/chaves/$bracketId'
      path: '/chaves/$bracketId'
      fullPath: '/chaves/$bracketId'
      preLoaderRoute: typeof ChavesBracketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/$slug': {
      id: '/campeonatos/$slug'
      path: '/campeonatos/$slug'
      fullPath: '/campeonatos/$slug'
      preLoaderRoute: typeof CampeonatosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/premiacoes': {
      id: '/admin/premiacoes'
      path: '/premiacoes'
      fullPath: '/admin/premiacoes'
      preLoaderRoute: typeof AdminPremiacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inscricoes': {
      id: '/admin/inscricoes'
      path: '/inscricoes'
      fullPath: '/admin/inscricoes'
      preLoaderRoute: typeof AdminInscricoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administradores': {
      id: '/admin/administradores'
      path: '/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdministradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staffs/': {
      id: '/admin/staffs/'
      path: '/staffs'
      fullPath: '/admin/staffs/'
      preLoaderRoute: typeof AdminStaffsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chaves/': {
      id: '/admin/chaves/'
      path: '/chaves'
      fullPath: '/admin/chaves/'
      preLoaderRoute: typeof AdminChavesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campeonatos/': {
      id: '/admin/campeonatos/'
      path: '/campeonatos'
      fullPath: '/admin/campeonatos/'
      preLoaderRoute: typeof AdminCampeonatosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/cadastro/$token': {
      id: '/staff/cadastro/$token'
      path: '/staff/cadastro/$token'
      fullPath: '/staff/cadastro/$token'
      preLoaderRoute: typeof StaffCadastroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premiacao/cadastro/$token': {
      id: '/premiacao/cadastro/$token'
      path: '/premiacao/cadastro/$token'
      fullPath: '/premiacao/cadastro/$token'
      preLoaderRoute: typeof PremiacaoCadastroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitro/cadastro/$token': {
      id: '/arbitro/cadastro/$token'
      path: '/arbitro/cadastro/$token'
      fullPath: '/arbitro/cadastro/$token'
      preLoaderRoute: typeof ArbitroCadastroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-transfer-auth': {
      id: '/api/public/asaas-transfer-auth'
      path: '/api/public/asaas-transfer-auth'
      fullPath: '/api/public/asaas-transfer-auth'
      preLoaderRoute: typeof ApiPublicAsaasTransferAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staffs/$staffId': {
      id: '/admin/staffs/$staffId'
      path: '/staffs/$staffId'
      fullPath: '/admin/staffs/$staffId'
      preLoaderRoute: typeof AdminStaffsStaffIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portaria/$id': {
      id: '/admin/portaria/$id'
      path: '/portaria/$id'
      fullPath: '/admin/portaria/$id'
      preLoaderRoute: typeof AdminPortariaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chaves/$bracketId': {
      id: '/admin/chaves/$bracketId'
      path: '/chaves/$bracketId'
      fullPath: '/admin/chaves/$bracketId'
      preLoaderRoute: typeof AdminChavesBracketIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias/$categoryId': {
      id: '/admin/categorias/$categoryId'
      path: '/categorias/$categoryId'
      fullPath: '/admin/categorias/$categoryId'
      preLoaderRoute: typeof AdminCategoriasCategoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campeonatos/$id': {
      id: '/admin/campeonatos/$id'
      path: '/campeonatos/$id'
      fullPath: '/admin/campeonatos/$id'
      preLoaderRoute: typeof AdminCampeonatosIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdministradoresRoute: typeof AdminAdministradoresRoute
  AdminInscricoesRoute: typeof AdminInscricoesRoute
  AdminPremiacoesRoute: typeof AdminPremiacoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCampeonatosIdRoute: typeof AdminCampeonatosIdRoute
  AdminCategoriasCategoryIdRoute: typeof AdminCategoriasCategoryIdRoute
  AdminChavesBracketIdRoute: typeof AdminChavesBracketIdRoute
  AdminPortariaIdRoute: typeof AdminPortariaIdRoute
  AdminStaffsStaffIdRoute: typeof AdminStaffsStaffIdRoute
  AdminCampeonatosIndexRoute: typeof AdminCampeonatosIndexRoute
  AdminChavesIndexRoute: typeof AdminChavesIndexRoute
  AdminStaffsIndexRoute: typeof AdminStaffsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministradoresRoute: AdminAdministradoresRoute,
  AdminInscricoesRoute: AdminInscricoesRoute,
  AdminPremiacoesRoute: AdminPremiacoesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCampeonatosIdRoute: AdminCampeonatosIdRoute,
  AdminCategoriasCategoryIdRoute: AdminCategoriasCategoryIdRoute,
  AdminChavesBracketIdRoute: AdminChavesBracketIdRoute,
  AdminPortariaIdRoute: AdminPortariaIdRoute,
  AdminStaffsStaffIdRoute: AdminStaffsStaffIdRoute,
  AdminCampeonatosIndexRoute: AdminCampeonatosIndexRoute,
  AdminChavesIndexRoute: AdminChavesIndexRoute,
  AdminStaffsIndexRoute: AdminStaffsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  TabelasRoute: TabelasRoute,
  CampeonatosSlugRoute: CampeonatosSlugRoute,
  ChavesBracketIdRoute: ChavesBracketIdRoute,
  IngressosSlugRoute: IngressosSlugRoute,
  InscricaoCategoryIdRoute: InscricaoCategoryIdRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffPainelRoute: StaffPainelRoute,
  SucessoVoucherRoute: SucessoVoucherRoute,
  VoucherIdRoute: VoucherIdRoute,
  CampeonatosIndexRoute: CampeonatosIndexRoute,
  VoucherIndexRoute: VoucherIndexRoute,
  ApiPublicAsaasTransferAuthRoute: ApiPublicAsaasTransferAuthRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ArbitroCadastroTokenRoute: ArbitroCadastroTokenRoute,
  PremiacaoCadastroTokenRoute: PremiacaoCadastroTokenRoute,
  StaffCadastroTokenRoute: StaffCadastroTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
