/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoucherIndexRouteImport } from './routes/voucher.index'
import { Route as CampeonatosIndexRouteImport } from './routes/campeonatos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VoucherIdRouteImport } from './routes/voucher.$id'
import { Route as SucessoVoucherRouteImport } from './routes/sucesso.$voucher'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as InscricaoCategoryIdRouteImport } from './routes/inscricao.$categoryId'
import { Route as CampeonatosSlugRouteImport } from './routes/campeonatos.$slug'
import { Route as AdminInscricoesRouteImport } from './routes/admin.inscricoes'
import { Route as AdminAdministradoresRouteImport } from './routes/admin.administradores'
import { Route as AdminCampeonatosIndexRouteImport } from './routes/admin.campeonatos.index'
import { Route as StaffCadastroTokenRouteImport } from './routes/staff.cadastro.$token'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as AdminCategoriasCategoryIdRouteImport } from './routes/admin.categorias.$categoryId'
import { Route as AdminCampeonatosIdRouteImport } from './routes/admin.campeonatos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherIndexRoute = VoucherIndexRouteImport.update({
  id: '/voucher/',
  path: '/voucher/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosIndexRoute = CampeonatosIndexRouteImport.update({
  id: '/campeonatos/',
  path: '/campeonatos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VoucherIdRoute = VoucherIdRouteImport.update({
  id: '/voucher/$id',
  path: '/voucher/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoVoucherRoute = SucessoVoucherRouteImport.update({
  id: '/sucesso/$voucher',
  path: '/sucesso/$voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoCategoryIdRoute = InscricaoCategoryIdRouteImport.update({
  id: '/inscricao/$categoryId',
  path: '/inscricao/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosSlugRoute = CampeonatosSlugRouteImport.update({
  id: '/campeonatos/$slug',
  path: '/campeonatos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInscricoesRoute = AdminInscricoesRouteImport.update({
  id: '/inscricoes',
  path: '/inscricoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministradoresRoute = AdminAdministradoresRouteImport.update({
  id: '/administradores',
  path: '/administradores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampeonatosIndexRoute = AdminCampeonatosIndexRouteImport.update({
  id: '/campeonatos/',
  path: '/campeonatos/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffCadastroTokenRoute = StaffCadastroTokenRouteImport.update({
  id: '/staff/cadastro/$token',
  path: '/staff/cadastro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasCategoryIdRoute =
  AdminCategoriasCategoryIdRouteImport.update({
    id: '/categorias/$categoryId',
    path: '/categorias/$categoryId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCampeonatosIdRoute = AdminCampeonatosIdRouteImport.update({
  id: '/campeonatos/$id',
  path: '/campeonatos/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/inscricoes': typeof AdminInscricoesRoute
  '/campeonatos/$slug': typeof CampeonatosSlugRoute
  '/inscricao/$categoryId': typeof InscricaoCategoryIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/sucesso/$voucher': typeof SucessoVoucherRoute
  '/voucher/$id': typeof VoucherIdRoute
  '/admin/': typeof AdminIndexRoute
  '/campeonatos/': typeof CampeonatosIndexRoute
  '/voucher/': typeof VoucherIndexRoute
  '/admin/campeonatos/$id': typeof AdminCampeonatosIdRoute
  '/admin/categorias/$categoryId': typeof AdminCategoriasCategoryIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/staff/cadastro/$token': typeof StaffCadastroTokenRoute
  '/admin/campeonatos/': typeof AdminCampeonatosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/inscricoes': typeof AdminInscricoesRoute
  '/campeonatos/$slug': typeof CampeonatosSlugRoute
  '/inscricao/$categoryId': typeof InscricaoCategoryIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/sucesso/$voucher': typeof SucessoVoucherRoute
  '/voucher/$id': typeof VoucherIdRoute
  '/admin': typeof AdminIndexRoute
  '/campeonatos': typeof CampeonatosIndexRoute
  '/voucher': typeof VoucherIndexRoute
  '/admin/campeonatos/$id': typeof AdminCampeonatosIdRoute
  '/admin/categorias/$categoryId': typeof AdminCategoriasCategoryIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/staff/cadastro/$token': typeof StaffCadastroTokenRoute
  '/admin/campeonatos': typeof AdminCampeonatosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/inscricoes': typeof AdminInscricoesRoute
  '/campeonatos/$slug': typeof CampeonatosSlugRoute
  '/inscricao/$categoryId': typeof InscricaoCategoryIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/sucesso/$voucher': typeof SucessoVoucherRoute
  '/voucher/$id': typeof VoucherIdRoute
  '/admin/': typeof AdminIndexRoute
  '/campeonatos/': typeof CampeonatosIndexRoute
  '/voucher/': typeof VoucherIndexRoute
  '/admin/campeonatos/$id': typeof AdminCampeonatosIdRoute
  '/admin/categorias/$categoryId': typeof AdminCategoriasCategoryIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/staff/cadastro/$token': typeof StaffCadastroTokenRoute
  '/admin/campeonatos/': typeof AdminCampeonatosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/administradores'
    | '/admin/inscricoes'
    | '/campeonatos/$slug'
    | '/inscricao/$categoryId'
    | '/staff/login'
    | '/sucesso/$voucher'
    | '/voucher/$id'
    | '/admin/'
    | '/campeonatos/'
    | '/voucher/'
    | '/admin/campeonatos/$id'
    | '/admin/categorias/$categoryId'
    | '/api/public/asaas-webhook'
    | '/staff/cadastro/$token'
    | '/admin/campeonatos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/administradores'
    | '/admin/inscricoes'
    | '/campeonatos/$slug'
    | '/inscricao/$categoryId'
    | '/staff/login'
    | '/sucesso/$voucher'
    | '/voucher/$id'
    | '/admin'
    | '/campeonatos'
    | '/voucher'
    | '/admin/campeonatos/$id'
    | '/admin/categorias/$categoryId'
    | '/api/public/asaas-webhook'
    | '/staff/cadastro/$token'
    | '/admin/campeonatos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/administradores'
    | '/admin/inscricoes'
    | '/campeonatos/$slug'
    | '/inscricao/$categoryId'
    | '/staff/login'
    | '/sucesso/$voucher'
    | '/voucher/$id'
    | '/admin/'
    | '/campeonatos/'
    | '/voucher/'
    | '/admin/campeonatos/$id'
    | '/admin/categorias/$categoryId'
    | '/api/public/asaas-webhook'
    | '/staff/cadastro/$token'
    | '/admin/campeonatos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  CampeonatosSlugRoute: typeof CampeonatosSlugRoute
  InscricaoCategoryIdRoute: typeof InscricaoCategoryIdRoute
  StaffLoginRoute: typeof StaffLoginRoute
  SucessoVoucherRoute: typeof SucessoVoucherRoute
  VoucherIdRoute: typeof VoucherIdRoute
  CampeonatosIndexRoute: typeof CampeonatosIndexRoute
  VoucherIndexRoute: typeof VoucherIndexRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  StaffCadastroTokenRoute: typeof StaffCadastroTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher/': {
      id: '/voucher/'
      path: '/voucher'
      fullPath: '/voucher/'
      preLoaderRoute: typeof VoucherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/': {
      id: '/campeonatos/'
      path: '/campeonatos'
      fullPath: '/campeonatos/'
      preLoaderRoute: typeof CampeonatosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/voucher/$id': {
      id: '/voucher/$id'
      path: '/voucher/$id'
      fullPath: '/voucher/$id'
      preLoaderRoute: typeof VoucherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso/$voucher': {
      id: '/sucesso/$voucher'
      path: '/sucesso/$voucher'
      fullPath: '/sucesso/$voucher'
      preLoaderRoute: typeof SucessoVoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$categoryId': {
      id: '/inscricao/$categoryId'
      path: '/inscricao/$categoryId'
      fullPath: '/inscricao/$categoryId'
      preLoaderRoute: typeof InscricaoCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/$slug': {
      id: '/campeonatos/$slug'
      path: '/campeonatos/$slug'
      fullPath: '/campeonatos/$slug'
      preLoaderRoute: typeof CampeonatosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscricoes': {
      id: '/admin/inscricoes'
      path: '/inscricoes'
      fullPath: '/admin/inscricoes'
      preLoaderRoute: typeof AdminInscricoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administradores': {
      id: '/admin/administradores'
      path: '/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdministradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campeonatos/': {
      id: '/admin/campeonatos/'
      path: '/campeonatos'
      fullPath: '/admin/campeonatos/'
      preLoaderRoute: typeof AdminCampeonatosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/cadastro/$token': {
      id: '/staff/cadastro/$token'
      path: '/staff/cadastro/$token'
      fullPath: '/staff/cadastro/$token'
      preLoaderRoute: typeof StaffCadastroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias/$categoryId': {
      id: '/admin/categorias/$categoryId'
      path: '/categorias/$categoryId'
      fullPath: '/admin/categorias/$categoryId'
      preLoaderRoute: typeof AdminCategoriasCategoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campeonatos/$id': {
      id: '/admin/campeonatos/$id'
      path: '/campeonatos/$id'
      fullPath: '/admin/campeonatos/$id'
      preLoaderRoute: typeof AdminCampeonatosIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdministradoresRoute: typeof AdminAdministradoresRoute
  AdminInscricoesRoute: typeof AdminInscricoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCampeonatosIdRoute: typeof AdminCampeonatosIdRoute
  AdminCategoriasCategoryIdRoute: typeof AdminCategoriasCategoryIdRoute
  AdminCampeonatosIndexRoute: typeof AdminCampeonatosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministradoresRoute: AdminAdministradoresRoute,
  AdminInscricoesRoute: AdminInscricoesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCampeonatosIdRoute: AdminCampeonatosIdRoute,
  AdminCategoriasCategoryIdRoute: AdminCategoriasCategoryIdRoute,
  AdminCampeonatosIndexRoute: AdminCampeonatosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  CampeonatosSlugRoute: CampeonatosSlugRoute,
  InscricaoCategoryIdRoute: InscricaoCategoryIdRoute,
  StaffLoginRoute: StaffLoginRoute,
  SucessoVoucherRoute: SucessoVoucherRoute,
  VoucherIdRoute: VoucherIdRoute,
  CampeonatosIndexRoute: CampeonatosIndexRoute,
  VoucherIndexRoute: VoucherIndexRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  StaffCadastroTokenRoute: StaffCadastroTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
